#!/usr/bin/env python3
"""Generate docsify _sidebar.md from markdown files recursively."""

from __future__ import annotations

from pathlib import Path
import argparse


IGNORED_DIRS = {
    ".git",
    ".github",
    ".vscode",
    "node_modules",
}
IGNORED_FILES = {
    "_sidebar.md",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate docsify sidebar")
    parser.add_argument("--root", default=".", help="Docs root directory")
    parser.add_argument("--output", default="_sidebar.md", help="Sidebar output path")
    return parser.parse_args()


def is_markdown(path: Path) -> bool:
    return path.is_file() and path.suffix.lower() == ".md"


def should_skip_dir(path: Path) -> bool:
    return path.name in IGNORED_DIRS


def should_skip_file(path: Path) -> bool:
    return path.name in IGNORED_FILES


def link_path(root: Path, file_path: Path) -> str:
    return file_path.relative_to(root).as_posix()


def item_title(root: Path, file_path: Path) -> str:
    if file_path.name.lower() == "readme.md" and file_path.parent == root:
        return "首页"
    if file_path.name.lower() == "readme.md":
        return file_path.parent.name
    return file_path.stem


def render_directory(lines: list[str], root: Path, current: Path, indent: int) -> None:
    child_dirs = sorted(
        [p for p in current.iterdir() if p.is_dir() and not should_skip_dir(p)],
        key=lambda p: p.name.lower(),
    )
    child_files = sorted(
        [
            p
            for p in current.iterdir()
            if is_markdown(p)
            and not should_skip_file(p)
            and p.name.lower() != "readme.md"
        ],
        key=lambda p: p.name.lower(),
    )

    for file_path in child_files:
        prefix = "  " * indent
        lines.append(f"{prefix}- [{item_title(root, file_path)}]({link_path(root, file_path)})")

    for dir_path in child_dirs:
        prefix = "  " * indent
        readme = dir_path / "README.md"
        if readme.exists():
            lines.append(f"{prefix}- [{dir_path.name}]({link_path(root, readme)})")
        else:
            lines.append(f"{prefix}- {dir_path.name}")
        render_directory(lines, root, dir_path, indent + 1)


def generate_sidebar(root: Path) -> str:
    lines: list[str] = [
        "<!-- AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY. -->",
        "<!-- Generated by .github/scripts/generate_sidebar.py -->",
    ]

    root_readme = root / "README.md"
    if root_readme.exists():
        lines.append(f"- [{item_title(root, root_readme)}](/README.md)")

    render_directory(lines, root, root, indent=0)
    return "\n".join(lines).strip() + "\n"


def main() -> None:
    args = parse_args()
    root = Path(args.root).resolve()
    output = (root / args.output).resolve()

    content = generate_sidebar(root)
    output.write_text(content, encoding="utf-8")
    print(f"Generated sidebar: {output}")


if __name__ == "__main__":
    main()
